"use client";

import { motion } from "framer-motion";
import {
  Shield,
  AlertTriangle,
  Download,
  FileText,
} from "lucide-react";

export default function ReportPage() {
  const vulnerabilities = [
    {
      issue: "Reflected XSS",
      severity: "Critical",
    },
    {
      issue: "Missing CSP Header",
      severity: "High",
    },
    {
      issue: "Weak TLS Configuration",
      severity: "High",
    },
    {
      issue: "Missing HSTS Header",
      severity: "Medium",
    },
    {
      issue: "Cookie Security Warning",
      severity: "Low",
    },
  ];

  return (
    <div className="min-h-screen bg-[#050816] text-white p-8">

      <div className="max-w-7xl mx-auto">

        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-10"
        >
          <div className="flex items-center gap-3 mb-4">
            <FileText className="text-orange-500" size={40} />
            <h1 className="text-5xl font-bold">
              Security Report
            </h1>
          </div>

          <p className="text-gray-400">
            Comprehensive vulnerability assessment report
            generated by vulNexa.
          </p>
        </motion.div>

        {/* Website Info */}
        <div className="bg-white/5 border border-white/10 rounded-3xl p-6 mb-8">

          <h2 className="text-2xl font-bold mb-4">
            Scan Information
          </h2>

          <div className="grid md:grid-cols-2 gap-4 text-gray-300">

            <p>
              Website:
              <span className="text-white ml-2">
                https://example.com
              </span>
            </p>

            <p>
              Scan Date:
              <span className="text-white ml-2">
                02 Oct 2026
              </span>
            </p>

          </div>

        </div>

        {/* Security Score */}
        <div className="bg-white/5 border border-white/10 rounded-3xl p-8 mb-8">

          <h2 className="text-2xl font-bold mb-6">
            Security Score
          </h2>

          <div className="flex justify-center">

            <div className="w-56 h-56 rounded-full border-8 border-orange-500 flex items-center justify-center">

              <div className="text-center">

                <h2 className="text-6xl font-bold">
                  92
                </h2>

                <p className="text-gray-400">
                  Excellent
                </p>

              </div>

            </div>

          </div>

        </div>

        {/* Summary Cards */}
        <div className="grid md:grid-cols-4 gap-6 mb-10">

          <div className="bg-red-500/10 border border-red-500/20 rounded-3xl p-6">
            <h3 className="text-red-400 text-lg">
              Critical
            </h3>
            <p className="text-4xl font-bold mt-2">
              1
            </p>
          </div>

          <div className="bg-orange-500/10 border border-orange-500/20 rounded-3xl p-6">
            <h3 className="text-orange-400 text-lg">
              High
            </h3>
            <p className="text-4xl font-bold mt-2">
              3
            </p>
          </div>

          <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-3xl p-6">
            <h3 className="text-yellow-400 text-lg">
              Medium
            </h3>
            <p className="text-4xl font-bold mt-2">
              5
            </p>
          </div>

          <div className="bg-green-500/10 border border-green-500/20 rounded-3xl p-6">
            <h3 className="text-green-400 text-lg">
              Low
            </h3>
            <p className="text-4xl font-bold mt-2">
              8
            </p>
          </div>

        </div>

        {/* Vulnerability Table */}
        <div className="bg-white/5 border border-white/10 rounded-3xl p-8 mb-10">

          <h2 className="text-2xl font-bold mb-6">
            Vulnerability Details
          </h2>

          <div className="overflow-x-auto">

            <table className="w-full">

              <thead>
                <tr className="border-b border-white/10 text-left">
                  <th className="pb-4">Issue</th>
                  <th className="pb-4">Severity</th>
                </tr>
              </thead>

              <tbody>

                {vulnerabilities.map((item, index) => (
                  <tr
                    key={index}
                    className="border-b border-white/5"
                  >
                    <td className="py-4">
                      {item.issue}
                    </td>

                    <td className="py-4">

                      <span
                        className={`px-3 py-1 rounded-full text-sm ${
                          item.severity === "Critical"
                            ? "bg-red-500/20 text-red-400"
                            : item.severity === "High"
                            ? "bg-orange-500/20 text-orange-400"
                            : item.severity === "Medium"
                            ? "bg-yellow-500/20 text-yellow-400"
                            : "bg-green-500/20 text-green-400"
                        }`}
                      >
                        {item.severity}
                      </span>

                    </td>

                  </tr>
                ))}

              </tbody>

            </table>

          </div>

        </div>

        {/* AI Recommendations */}
        <div className="bg-white/5 border border-white/10 rounded-3xl p-8 mb-10">

          <div className="flex items-center gap-3 mb-6">
            <Shield className="text-orange-500" />
            <h2 className="text-2xl font-bold">
              AI Recommendations
            </h2>
          </div>

          <div className="space-y-4 text-gray-300">

            <div>
              ✓ Add Content Security Policy (CSP)
            </div>

            <div>
              ✓ Enable HSTS Protection
            </div>

            <div>
              ✓ Upgrade TLS Configuration
            </div>

            <div>
              ✓ Sanitize User Inputs
            </div>

            <div>
              ✓ Use Secure Cookie Flags
            </div>

          </div>

        </div>

        {/* Download Report */}
        <div className="flex justify-center">

          <button
            onClick={() =>
              alert("PDF Download Coming Soon")
            }
            className="bg-orange-500 hover:bg-orange-600 px-8 py-4 rounded-xl flex items-center gap-3 font-semibold"
          >
            <Download size={20} />
            Download PDF Report
          </button>

        </div>

      </div>

    </div>
  );
}